name: Provision EC2
run-name: ${{ github.actor }} created EC2
on: [push]
jobs:
  Terraform:
    runs-on: ubuntu-20.04
    steps:
      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.0
        with:
          terraform_version: 1.3.1
      - run: terraform --version
      - name: checkout repo code
        uses: actions/checkout@v3
      - run: terraform init
      - run: terraform plan
      - run: terraform apply --auto-approve
